Origin/feature/hud overheat
TFS-Spring-2022/Spring2022_Capstone pull request #39
Opened 2023-07-13 02:24 UTC by kaitlynli64

removed all the stuff from the previous PR that was not needed

2023-07-14 19:15 UTC, victor-ulloa requested changes
Please keep these comments in mind for the other PR that's open. Fix it here then update the other PR (#40). 
Also, there are merge conflicts due to our last approved PR. Make sure everything works after the merge.

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Blueprints/BP_BaseCharacter.uasset
What is this for? we already have a BP_Player

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Blueprints/PickUps/BP_PickUp_Gun.uasset
what's this for? we already have both weapon types as BPs

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Inputs/Actions/IA_Crouch.uasset
Remove changes. There should be no modification on this file.

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Inputs/Actions/IA_Jump.uasset
Remove changes. There should be no modification on this file.

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Inputs/Actions/IA_Look.uasset
Remove changes. There should be no modification on this file.

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Inputs/Actions/IA_Move.uasset
Remove changes. There should be no modification on this file.

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Inputs/Actions/IA_Sprint.uasset
Remove changes. There should be no modification on this file.

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Widgets/W_HealthBar.uasset
NAMING CONVENTION ->>>>>>>>>>>> WBP -> Widget Blueprint.
All naming conventions are in the guidelines or just look at the other files of the same type

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Widgets/W_PlayerHUD.uasset
NAMING CONVENTION ->>>>>>>>>>>> WBP -> Widget Blueprint.
All naming conventions are in the guidelines or just look at the other files of the same type

2023-07-14 19:15 UTC, victor-ulloa commented on Content/Widgets/W_PlayerHUD.uasset
Why do we have a new HUD? There was one created/being used already

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/Player/PlayerCharacter.h
> +	AWeaponBase* GetActiveWeapon() const;
is this being used? otherwise, delete.
If it's being used it should be a public function

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/UI/HUD/HUDWidget.cpp
> +void UHUDWidget::OnWeaponOverheatChanged(bool IsOverheat)
????

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/UI/HUD/HUDWidget.h
> +		void OnWeaponChargeChanged(float ChargeValue);
delete extra spaces

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/UI/HUD/HUDWidget.h
> +		void OnWeaponOverheatChanged(bool IsOverheat);
delete extra spaces

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/UI/HUD/HUDWidget.h
> +		void OnWeaponSwitched(AWeaponBase* SwitchedWeapon);
delete extra spaces

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/Weapon/SemiAutomaticWeapon.cpp
> +			if (OnWeaponChargeChangedDelegate.IsBound())
There's no need to check if it's bound. Not sure if it's the same Execute() call but check on documentation to fix this.
Yes, I made the same mistake before and have kept an eye on it to fix it.

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/Weapon/ShotgunWeapon.cpp
> +			if (OnWeaponChargeChangedDelegate.IsBound())
There's no need to check if it's bound. Not sure if it's the same Execute() call but check on documentation to fix this.
Yes, I made the same mistake before and have kept an eye on it to fix it.

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/Weapon/WeaponBase.cpp
> +	if (OnWeaponOverheatChangedDelegate.IsBound())
There's no need to check if it's bound. Not sure if it's the same Execute() call but check on documentation to fix this.
Yes, I made the same mistake before and have kept an eye on it to fix it.

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/Weapon/WeaponBase.cpp
> +	if (OnWeaponOverheatChangedDelegate.IsBound())
There's no need to check if it's bound. Not sure if it's the same Execute() call but check on documentation to fix this.
Yes, I made the same mistake before and have kept an eye on it to fix it.

2023-07-14 19:15 UTC, victor-ulloa commented on Source/Spring2022_Capstone/Weapon/WeaponBase.cpp
> +	if (OnWeaponChargeChangedDelegate.IsBound())
There's no need to check if it's bound. Not sure if it's the same Execute() call but check on documentation to fix this.
Yes, I made the same mistake before and have kept an eye on it to fix it.

2023-07-17 18:39 UTC, kaitlynli64 commented on Content/Blueprints/BP_BaseCharacter.uasset
will delete. Do not know why it was created...

2023-07-17 18:40 UTC, kaitlynli64 commented on Content/Blueprints/PickUps/BP_PickUp_Gun.uasset
Will delete.

2023-07-17 18:40 UTC, kaitlynli64 commented on Content/Inputs/Actions/IA_Crouch.uasset
I removed the extra one I created, did not touch the one being used.

2023-07-17 18:40 UTC, kaitlynli64 commented on Content/Inputs/Actions/IA_Jump.uasset
I removed the extra one I created, did not touch the one being used.

2023-07-17 18:40 UTC, kaitlynli64 commented on Content/Inputs/Actions/IA_Look.uasset
I removed the extra one I created, did not touch the one being used.

2023-07-17 18:43 UTC, kaitlynli64 commented on Content/Inputs/Actions/IA_Move.uasset
I removed the extra one I created, did not touch the one being used.

2023-07-17 18:43 UTC, kaitlynli64 commented on Content/Inputs/Actions/IA_Sprint.uasset
I removed the extra one I created, did not touch the one being used.

2023-07-20 21:34 UTC, closed without merging